server:
  port: "8080"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "gpan"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  useSSL: false
  bucket: "gpan"
